### ISSUE TITLE
rbind doesnt work.

### ISSUE THREAD

**Issue by amboton1** [EasyD/IntroToDataScience#2]
when trying the line : 

data.combined = rbind(train, test.survived)

i get an error : 

Error in match.names(clabs, names(xi)) : 
  names do not match previous names

**Comment by NiallMag** [comment]
This is because the column names in the .csv files have a capital letter at the start whereas the R code does not. Changing the column names in the .csv files will fix this

**Comment by nathantum** [comment]
I would rather change the S in the R code. 

test.survived <- data.frame(Survived = rep("None", nrow(test)), test[,])

**Comment by EasyD** [comment]
Unfortunately, this would require changing the capitalization everywhere in all the files. My suggestion - which include in the video basic info - is to use the CSVs and files from the GitHub. The code will produce valid submissions.
